#!/bin/sh

echo "Switching to branch main"
git checkout main

echo "Building app"
yarn build

echo "Deploying files to server"
rsync -avP out/ gareth@garethfield.website:/var/www/dot-eater/
echo "Deployment complete"